# Generated by Django 4.0.4 on 2022-06-02 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0004_cart_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='user',
        ),
    ]
