# Generated by Django 4.0.4 on 2022-06-03 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='zipcode',
            field=models.IntegerField(null=True),
        ),
    ]
