# Generated by Django 4.0.4 on 2022-06-11 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders1', '0003_alter_order_payment_alter_orderproduct_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Shipped', 'Shipped'), ('Out for Delivery', 'Out for Delivey'), ('Delivered', 'Delivered')], default='New', max_length=20),
        ),
    ]
