# Generated by Django 4.0.4 on 2022-06-10 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_account_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
