# Generated by Django 4.0.4 on 2022-05-28 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlists', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='wishlist_id',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
